In [8]:
import cv2
import numpy as np

image_hsv = None   # global ;(
pixel = (20,60,80) # some stupid default

# mouse callback function
def pick_color(event,x,y,flags,param):
    if event == cv2.EVENT_LBUTTONDOWN:
        pixel = image_hsv[y,x]

        #you might want to adjust the ranges(+-10, etc):
        upper =  np.array([pixel[0] + 10, pixel[1] + 10, pixel[2] + 40])
        lower =  np.array([pixel[0] - 10, pixel[1] - 10, pixel[2] - 40])
        print(pixel, lower, upper)

        image_mask = cv2.inRange(image_hsv,lower,upper)
        cv2.imshow("mask",image_mask)

def main():
    import sys
    global image_hsv, pixel # so we can use it in mouse callback

    image_src = cv2.imread("./result_img/LF10_2.tiff")  # pick.py my.png
    height, width, depth = image_src.shape
    newY, newX = int(height/5), int(width/5)
    image_src = cv2.resize(image_src,(newX, newY))
    if image_src is None:
        print ("the image read is None............")
        return

    cv2.imshow("bgr",image_src)

    ## NEW ##
    cv2.namedWindow('hsv',cv2.WINDOW_NORMAL)
    cv2.setMouseCallback('bgr', pick_color)

    # now click into the hsv img , and look at values:
    image_hsv = cv2.cvtColor(image_src,cv2.COLOR_BGR2HSV)
    cv2.imshow("hsv",image_hsv)

    cv2.waitKey(0)
    cv2.destroyAllWindows()
    cv2.waitKey(1)

if __name__=='__main__':
    main()

[ 12  41 223] [  2  31 183] [ 22  51 263]
[  5  48 228] [ -5  38 188] [ 15  58 268]
[177  67 212] [167  57 172] [187  77 252]
[170  74 206] [160  64 166] [180  84 246]
[158  58 229] [148  48 189] [168  68 269]
[159  59 233] [149  49 193] [169  69 273]
[159  66 241] [149  56 201] [169  76 281]
[161  66 243] [151  56 203] [171  76 283]
[162  78 234] [152  68 194] [172  88 274]
[159  61 238] [149  51 198] [169  71 278]
[160  62 238] [150  52 198] [170  72 278]
[161  49 241] [151  39 201] [171  59 281]
[165  40 241] [155  30 201] [175  50 281]
[160  35 246] [150  25 206] [170  45 286]
[164  38 234] [154  28 194] [174  48 274]
[160  71 227] [150  61 187] [170  81 267]


In [3]:
cv2.resize

<function resize>

In [2]:
os.getcwd()

NameError: name 'os' is not defined

In [3]:
import os

In [4]:
os.getcwd()


'/Users/pengfoen/Documents/Research/UW_experiment/Turing pattern/spots_counting'

In [5]:
cv2.imread("./result_img/rto_4.tiff")

array([[[230, 232, 234],
        [230, 232, 234],
        [231, 231, 233],
        ...,
        [231, 232, 232],
        [232, 231, 232],
        [233, 230, 232]],

       [[232, 232, 234],
        [232, 231, 234],
        [231, 231, 235],
        ...,
        [232, 232, 233],
        [232, 232, 233],
        [232, 231, 234]],

       [[234, 231, 234],
        [233, 231, 235],
        [232, 230, 235],
        ...,
        [233, 233, 233],
        [232, 233, 234],
        [231, 233, 234]],

       ...,

       [[230, 233, 234],
        [230, 232, 234],
        [230, 231, 234],
        ...,
        [227, 235, 233],
        [226, 234, 232],
        [226, 233, 231]],

       [[232, 232, 234],
        [231, 231, 234],
        [231, 230, 234],
        ...,
        [225, 234, 233],
        [225, 233, 232],
        [225, 233, 232]],

       [[233, 231, 234],
        [232, 230, 234],
        [232, 229, 234],
        ...,
        [225, 234, 233],
        [225, 233, 233],
        [225, 233, 233]]