In [2]:
import cv2
import numpy as np

image_hsv = None   # global ;(
pixel = (20,60,80) # some stupid default

# mouse callback function
def pick_color(event,x,y,flags,param):
    if event == cv2.EVENT_LBUTTONDOWN:
        pixel = image_hsv[y,x]

        #you might want to adjust the ranges(+-10, etc):
        upper =  np.array([pixel[0] + 10, pixel[1] + 10, pixel[2] + 40])
        lower =  np.array([pixel[0] - 10, pixel[1] - 10, pixel[2] - 40])
        print(pixel, lower, upper)

        image_mask = cv2.inRange(image_hsv,lower,upper)
        cv2.imshow("mask",image_mask)

def main():
    import sys
    global image_hsv, pixel # so we can use it in mouse callback

    image_src = cv2.imread("rto_4.tiff")  # pick.py my.png
    height, width, depth = image_src.shape
    newY, newX = int(height/5), int(width/5)
    image_src = cv2.resize(image_src,(newX, newY))
    if image_src is None:
        print ("the image read is None............")
        return

    cv2.imshow("bgr",image_src)

    ## NEW ##
    cv2.namedWindow('hsv',cv2.WINDOW_NORMAL)
    cv2.setMouseCallback('bgr', pick_color)

    # now click into the hsv img , and look at values:
    image_hsv = cv2.cvtColor(image_src,cv2.COLOR_BGR2HSV)
    cv2.imshow("hsv",image_hsv)

    cv2.waitKey(0)
    cv2.destroyAllWindows()
    cv2.waitKey(1)

if __name__=='__main__':
    main()

[ 16 126 220] [  6 116 180] [ 26 136 260]
[ 19 166 214] [  9 156 174] [ 29 176 254]
[ 19 163 218] [  9 153 178] [ 29 173 258]
[ 21 185 215] [ 11 175 175] [ 31 195 255]
[ 18 153 214] [  8 143 174] [ 28 163 254]
[ 13 173 199] [  3 163 159] [ 23 183 239]
[ 17 134 217] [  7 124 177] [ 27 144 257]
[ 19 155 215] [  9 145 175] [ 29 165 255]
[ 18 155 212] [  8 145 172] [ 28 165 252]
[  7 162 165] [ -3 152 125] [ 17 172 205]
[ 19 165 205] [  9 155 165] [ 29 175 245]
[ 20 182 216] [ 10 172 176] [ 30 192 256]
[ 20 146 218] [ 10 136 178] [ 30 156 258]
[ 20 153 208] [ 10 143 168] [ 30 163 248]
[ 20 149 217] [ 10 139 177] [ 30 159 257]
[ 14 191 180] [  4 181 140] [ 24 201 220]
[ 16 170 206] [  6 160 166] [ 26 180 246]
[ 13 178 195] [  3 168 155] [ 23 188 235]
[  5 157 153] [ -5 147 113] [ 15 167 193]
[  7 155 150] [ -3 145 110] [ 17 165 190]
[ 10 180 150] [  0 170 110] [ 20 190 190]
[  6 176 149] [ -4 166 109] [ 16 186 189]
[ 20 162 195] [ 10 152 155] [ 30 172 235]
[ 20 169 198] [ 10 159 158] [ 30 1

In [3]:
cv2.resize

<function resize>