In [ ]:
import cv2
import numpy as np

image_hsv = None   # global ;(
pixel = (20,60,80) # some stupid default

# mouse callback function
def pick_color(event,x,y,flags,param):
    if event == cv2.EVENT_LBUTTONDOWN:
        pixel = image_hsv[y,x]

        #you might want to adjust the ranges(+-10, etc):
        upper =  np.array([pixel[0] + 3, pixel[1] + 3, pixel[2] + 10])
        lower =  np.array([pixel[0] - 3, pixel[1] - 3, pixel[2] - 10])
        print(pixel, lower, upper)

        image_mask = cv2.inRange(image_hsv,lower,upper)
        cv2.imshow("mask",image_mask)

def main():
    import sys
    global image_hsv, pixel # so we can use it in mouse callback

    image_src = cv2.imread("./result_img/RTORNAi8_1.tiff")  # pick.py my.png
    height, width, depth = image_src.shape
    newY, newX = int(height/5), int(width/5)
    image_src = cv2.resize(image_src,(newX, newY))
    if image_src is None:
        print ("the image read is None............")
        return

    cv2.imshow("bgr",image_src)

    ## NEW ##
    cv2.namedWindow('hsv',cv2.WINDOW_NORMAL)
    cv2.setMouseCallback('bgr', pick_color)

    # now click into the hsv img , and look at values:
    image_hsv = cv2.cvtColor(image_src,cv2.COLOR_BGR2HSV)
    cv2.imshow("hsv",image_hsv)

    cv2.waitKey(0)
    cv2.destroyAllWindows()
    cv2.waitKey(1)

if __name__=='__main__':
    main()

[162 139 207] [159 136 197] [165 142 217]
[163 144 184] [160 141 174] [166 147 194]
[166 173 174] [163 170 164] [169 176 184]
[163 159 178] [160 156 168] [166 162 188]
[163 143 203] [160 140 193] [166 146 213]
[162 153 201] [159 150 191] [165 156 211]
[164 129 182] [161 126 172] [167 132 192]
[164 128 187] [161 125 177] [167 131 197]
[163 143 204] [160 140 194] [166 146 214]
[163 138 203] [160 135 193] [166 141 213]
[161 106 207] [158 103 197] [164 109 217]
[165 151 179] [162 148 169] [168 154 189]


In [3]:
cv2.resize

<function resize>

In [2]:
os.getcwd()

NameError: name 'os' is not defined

In [3]:
import os

In [4]:
os.getcwd()


'/Users/pengfoen/Documents/Research/UW_experiment/Turing pattern/spots_counting'

In [5]:
cv2.imread("./result_img/rto_4.tiff")

array([[[230, 232, 234],
        [230, 232, 234],
        [231, 231, 233],
        ...,
        [231, 232, 232],
        [232, 231, 232],
        [233, 230, 232]],

       [[232, 232, 234],
        [232, 231, 234],
        [231, 231, 235],
        ...,
        [232, 232, 233],
        [232, 232, 233],
        [232, 231, 234]],

       [[234, 231, 234],
        [233, 231, 235],
        [232, 230, 235],
        ...,
        [233, 233, 233],
        [232, 233, 234],
        [231, 233, 234]],

       ...,

       [[230, 233, 234],
        [230, 232, 234],
        [230, 231, 234],
        ...,
        [227, 235, 233],
        [226, 234, 232],
        [226, 233, 231]],

       [[232, 232, 234],
        [231, 231, 234],
        [231, 230, 234],
        ...,
        [225, 234, 233],
        [225, 233, 232],
        [225, 233, 232]],

       [[233, 231, 234],
        [232, 230, 234],
        [232, 229, 234],
        ...,
        [225, 234, 233],
        [225, 233, 233],
        [225, 233, 233]]